name: Bug 报告
description: 报告一个 Bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您报告这个 Bug！请填写以下信息帮助我们定位问题。
        
  - type: textarea
    id: description
    attributes:
      label: Bug 描述
      description: 清晰简洁地描述这个 Bug
      placeholder: 告诉我们发生了什么...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤
      description: 复现这个 Bug 的步骤
      placeholder: |
        1. 创建数据...
        2. 配置转换...
        3. 执行转换...
        4. 看到错误...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望行为
      description: 描述您期望发生什么
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 实际行为
      description: 描述实际发生了什么
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: 最小复现代码
      description: 如果可能，请提供最小复现代码
      render: python
      placeholder: |
        import polars as pl
        from qdata_transformer import PolarsFieldMappingTransformer
        
        data = pl.DataFrame({...})
        transformer = PolarsFieldMappingTransformer()
        result = transformer.execute(data, {...})

  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      description: 请提供您的环境信息
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - Python: 3.11.0
        - qdata-transformer: 1.0.0
        - polars: 0.20.0
        - duckdb: 0.9.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 错误日志
      description: 如有错误日志，请粘贴在这里
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      options:
        - label: 我已搜索现有 Issues，没有找到相同问题
          required: true
        - label: 我使用的是最新版本
          required: false
